spring:
  application:
    name: @application.name@
  data:
    mongodb:
      database: streamReaderApp
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
server:
  port: 8081
  servlet:
    context-path: /

springfox:
  documentation:
    enabled: true
